### ISSUE TITLE
Tooltip box clipped after filter

### ISSUE THREAD

**Issue by rnathanday** [kirschbombe/openbibl#22]
Certain tooltip boxes are being truncated after a filter operation. Steps to reproduce:

1. Navigate to http://rnathanday.github.io/openbibl/examples/otherEurope/otherEurope.xml
2. Click "Biblia Bohemica" in the TOC
3. Expand entire entry
4. Hover over "Jan Hus", notice that the full tooltip displays
5. Expand the "People" filter
6. Select "Jan Hus"
7. Expand the entire "Biblia Bohemica" entry
8. Hover over the "Jan Hus" link, notice that the tooltip is constrained in size by the margin of the enclosing p.bibliography element.

**Comment by kirschbombe** [comment]
Tested and had no issues.
